Repository mboersma/cluster-api-charts, pull requests merged in 2024-05, with the labels that each got.

#1 Update documentation with project details
  CONTRIBUTING.md
  OWNERS
  OWNERS_ALIASES
  README.md
  RELEASE.md
  SECURITY_CONTACTS
Labels: documentation

#4 Add Helm chart for AKS managed cluster
  .gitignore
  charts/azure-managed-cluster/.helmignore
  charts/azure-managed-cluster/Chart.yaml
  charts/azure-managed-cluster/templates/_helpers.tpl
  charts/azure-managed-cluster/templates/agentpools.yaml
  charts/azure-managed-cluster/templates/azureclusteridentity.yaml
  charts/azure-managed-cluster/templates/azuremanagedccontrolplane.yaml
  charts/azure-managed-cluster/templates/azuremanagedcluster.yaml
  charts/azure-managed-cluster/templates/cluster.yaml
  charts/azure-managed-cluster/templates/secret.yaml
  charts/azure-managed-cluster/values.yaml
Labels: kind/feature

#3 add aks-aso chart
  README.md
  charts/azure-aks-aso/.helmignore
  charts/azure-aks-aso/Chart.yaml
  charts/azure-aks-aso/README.md
  charts/azure-aks-aso/templates/_helpers.tpl
  charts/azure-aks-aso/templates/cluster.yaml
  charts/azure-aks-aso/templates/clusterclass.yaml
  charts/azure-aks-aso/templates/credentials.yaml
  charts/azure-aks-aso/values.yaml
Labels: kind/feature

#14 Update readme to use helm
  README.md
Labels: do-not-merge/hold
